{
 "title": "Solace broker",
 "description": "Analyse solace PubSub+ VPNs",
 "tags": [
  "solace",
  "broker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(up{group=\"Solace\"}, instance)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Broker status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 9, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Redundancy Status",
   "type": "stat",
   "description": "Redundancy status for High Availability support on this broker",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_redundancy_local_active{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "gauge",
   "description": "Network latency to HA mate, empty in case of no HA configured",
   "gridPos": { "h": 6, "w": 4, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "gauge",
   "description": "latency for disk read/write operations",
   "gridPos": { "h": 6, "w": 4, "x": 16, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "gauge",
   "description": "latency for CPU instructions  on the broker",
   "gridPos": { "h": 6, "w": 4, "x": 20, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 3, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(solace_system_version_currentload{instance=\"$instance\"} % 1000000000)/ 1000000"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 5, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(solace_system_version_currentload{instance=\"$instance\"} % 1000000)/ 100"
    }
   ]
  },
  {
   "type": "stat",
   "gridPos": { "h": 2, "w": 2, "x": 7, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "(solace_system_version_currentload{instance=\"$instance\"} % 1000)"
    }
   ]
  },
  {
   "title": "Connections Count",
   "type": "timeseries",
   "description": "Client Connections Count, per Vpn. Drill down into Vpn available",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "System Redundancy Config",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_redundancy_config{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "System Redundancy Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_redundancy_up{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "System Redundancy Role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_system_redundancy_role{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Bridges Admin Status",
   "type": "table-old",
   "description": "Bridges Administrative Status, drill down into Bridge available",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 14 },
   "targets": [
    {
     "expr": "label_replace(solace_bridge_admin_state{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "AdminState"
    }
   ]
  },
  {
   "title": "Config Sync State",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_syncstate{instance=\"$instance\",table_name=\"site\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Time in this state",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_timeinstateseconds{instance=\"$instance\",table_name=\"site\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Config Sync Role",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 18 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_ownership{instance=\"$instance\",table_name=\"site\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_rx_bytes_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_tx_bytes_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Transfer msgs IN",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_rx_msgs_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    }
   ]
  },
  {
   "title": "Transfer msgs OUT",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_tx_msgs_total{instance=\"$instance\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Spooled msgs",
   "type": "timeseries",
   "description": "Number of spooled messages on the broker, against max. quota of spool available",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(solace_system_spool_usage_msgs{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "spooled msgs {{instance_short}}"
    },
    {
     "expr": "label_replace(solace_system_spool_quota_msgs{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "quota {{instance_short}}"
    },
    {
     "expr": "label_replace(solace_vpn_spool_usage_msgs{instance=\"$instance\", vpn_name!~\"default\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "spooled msgs {{instance_short}} {{vpn_name}}"
    }
   ]
  },
  {
   "title": "Spooled bytes",
   "type": "timeseries",
   "description": "Amount of spooled data on the broker, against max. quota of spool available",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "label_replace(solace_system_spool_usage_bytes{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "spooled msgs {{instance_short}}"
    },
    {
     "expr": "label_replace(solace_system_spool_quota_bytes{instance=\"$instance\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "quota {{instance_short}}"
    },
    {
     "expr": "label_replace(solace_vpn_spool_usage_bytes{instance=\"$instance\", vpn_name!~\"default\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "spooled msgs {{instance_short}} {{vpn_name}}"
    },
    {
     "expr": "label_replace(solace_vpn_spool_quota_bytes{instance=\"$instance\", vpn_name!~\"default\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "quota {{instance_short}} {{vpn_name}}"
    }
   ]
  }
 ]
}