{
 "title": "Solace vpn",
 "description": "Analyse solace PubSub+ VPNs",
 "tags": [
  "solace",
  "vpn"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": {
     "query": "label_values(solace_up{group=\"Solace\"}, instance)"
    }
   },
   {
    "name": "vpn_name",
    "label": "VPN",
    "query": {
     "query": "label_values(solace_vpn_connections{instance=\"$instance\",group=\"Solace\"}, vpn_name)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "VPN Local Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_local_status{instance=\"$instance\",vpn_name=\"$vpn_name\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Config Sync Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 10, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_syncstate{instance=\"$instance\",table_name=\"$vpn_name\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Time in this state",
   "type": "stat",
   "description": "empty in case of Config State is not configured",
   "gridPos": { "h": 4, "w": 4, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_timeinstateseconds{instance=\"$instance\",table_name=\"$vpn_name\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Config Sync Role",
   "type": "stat",
   "description": "Part taken in the Config Sync setup, empty in case Config Sync is not configured",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_ownership{instance=\"$instance\",table_name=\"$vpn_name\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")"
    }
   ]
  },
  {
   "title": "Connection to concentrator",
   "type": "stat",
   "gridPos": { "h": 2, "w": 6, "x": 18, "y": 2 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(solace_broker_connected_to_concentrator{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=\"$instance\",vpn_name=\"$vpn_name\"}, \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": " {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Transfer volume / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_rx_bytes_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\") * 8",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    },
    {
     "expr": "label_replace(irate(solace_vpn_tx_bytes_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\") * 8",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Transfer Messages / sec",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_rx_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    },
    {
     "expr": "label_replace(irate(solace_vpn_tx_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "options": {
    "content": "\n## Clients\n\nlist of flashy/possible problematic clients\n\n\n\n"
   }
  },
  {
   "title": "Clients discarded msgs IN",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(irate(solace_client_rx_discarded_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[15m]) > 0) by (instance, vpn_name, client_username) or vector(0), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{client_username}} {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Clients discarded msgs OUT",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(irate(solace_client_tx_discarded_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[15m]) > 0) by (instance, vpn_name, client_username) or vector(0), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{client_username}} {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Clients slow subscriber",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(sum(solace_client_slow_subscriber{instance=\"$instance\",vpn_name=\"$vpn_name\"} > 0) by (instance, vpn_name, client_username), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{client_username}}  {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 }, "options": { "content": "## Queue\n\n\n" } },
  {
   "title": "Queues without consumer",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "label_replace(count_over_time((solace_queue_binds{instance=\"$instance\",vpn_name=\"$vpn_name\",queue_name!~\"leader.*\",queue_name!~\"api_stats_.*\"} < 1)[1m:1m]), \"instance_short\", \"$1$3\", \"instance\", \"(^.+)(?:.sbb.ch){1}(:\\\\d+)|(^[^:]+)(:\\\\d+)?\")",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Queue usage [% of quota]",
   "type": "timeseries",
   "description": "May be empty for OnPrem Broker",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solace_queue_spool_usage_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\"} / solace_queue_spool_quota_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\"} * 100",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Spool memory usage over vpn [% of quota]",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "100*solace_vpn_spool_usage_bytes{instance=\"$instance\", vpn_name=\"$vpn_name\"}/solace_vpn_spool_quota_bytes{instance=\"$instance\", vpn_name=\"$vpn_name\"}"
    }
   ]
  },
  {
   "title": "Spool messages over vpn",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "solace_vpn_spool_usage_msgs{instance=\"$instance\", vpn_name=\"$vpn_name\"}"
    }
   ]
  }
 ]
}