{
 "title": "Solace brokers",
 "description": "Analyse solace PubSub+ VPNs",
 "tags": [
  "solace",
  "broker"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance_short",
    "query": "label_values(solace_vpn_connections, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 0 },
   "repeat": "instance_short",
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 6 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 12 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 18 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 24 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 30 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "$instance_short status",
   "type": "gauge",
   "gridPos": { "h": 6, "w": 3, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(solace_up{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{instance_short}}"
    }
   ]
  },
  {
   "title": "client cons",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 4, "x": 3, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=~\"$instance_short.*\",vpn_name!~\"#.*\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}"
    }
   ]
  },
  {
   "title": "mate link latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 7, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(solace_system_mate_link_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "disk latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 9, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(solace_system_disk_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "compute latency",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 2, "x": 11, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(solace_system_compute_latency_avg_seconds{instance=~\"$instance_short.*\",job=\"solace-std\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Transfer volume OUT",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 13, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_tx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  },
  {
   "title": "Transfer volume IN",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 5, "x": 19, "y": 36 },
   "targets": [
    {
     "expr": "label_replace(rate(solace_vpn_rx_bytes_total{instance=~\"$instance_short.*\",vpn_name!~\"^#.+\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}"
    }
   ]
  }
 ]
}