{
 "title": "Solace vpn",
 "description": "Analyse solace PubSub+ VPNs",
 "tags": [
  "solace",
  "vpn"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(up{group=\"Solace\"}, instance)"
   },
   {
    "name": "vpn_name",
    "label": "VPN",
    "query": "label_values(solace_vpn_connections{instance=\"$instance\",group=\"Solace\"}, vpn_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "VPN Local Status",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 4, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_vpn_local_status{instance=\"$instance\",vpn_name=\"$vpn_name\",job=\"solace\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Config Sync Status",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_syncstate{instance=\"$instance\",table_name=\"$vpn_name\",job=\"solace\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Time in this state",
   "type": "stat",
   "description": "empty in case of Config State is not configured",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_timeinstateseconds{instance=\"$instance\",table_name=\"$vpn_name\",job=\"solace\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Config Sync Role",
   "type": "stat",
   "description": "Part taken in the Config Sync setup, empty in case Config Sync is not configured",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "targets": [
    {
     "expr": "label_replace(solace_configsync_table_ownership{instance=\"$instance\",table_name=\"$vpn_name\",job=\"solace\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")"
    }
   ]
  },
  {
   "title": "Client connections",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(solace_vpn_connections{instance=\"$instance\",vpn_name=\"$vpn_name\"}, \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": " {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Transfer volume / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_rx_bytes_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    },
    {
     "expr": "label_replace(irate(solace_vpn_tx_bytes_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "title": "Transfer Messages / sec",
   "type": "graph",
   "gridPos": { "h": 6, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(irate(solace_vpn_rx_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} IN"
    },
    {
     "expr": "label_replace(irate(solace_vpn_tx_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[5m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{vpn_name}}@{{instance_short}} OUT"
    }
   ]
  },
  {
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 21 },
   "content": "\n## Clients\n\nlist of flashy/possible problematic clients\n\n\n\n"
  },
  {
   "title": "Clients discarded msgs IN",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(count_over_time((irate(solace_client_rx_discarded_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[15m]) > 0)[1m:10s]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{client_username}} ({{client_name}}) {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Clients discarded msgs OUT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(count_over_time((irate(solace_client_tx_discarded_msgs_total{instance=\"$instance\",vpn_name=\"$vpn_name\"}[15m]) > 0)[1m:10s]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{client_username}} ({{client_name}}) {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  {
   "title": "Clients slow subscriber",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "label_replace(count_over_time((solace_client_slow_subscriber{instance=\"$instance\",vpn_name=\"$vpn_name\"} > 0)[5m:10s]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")",
     "legendFormat": "{{client_username}} ({{client_name}}) {{vpn_name}}@{{instance_short}}"
    }
   ]
  },
  { "type": "text", "gridPos": { "h": 2, "w": 24, "x": 0, "y": 36 }, "content": "## Queue\n\n\n" },
  {
   "title": "Queues without consumer",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 38 },
   "yaxes": [
    { "format": "short", "label": "number of queues" }
   ],
   "targets": [
    {
     "expr": "label_replace(count_over_time((irate(solace_queue_binds{instance=\"$instance\",vpn_name=\"$vpn_name\"}[15m]) < 1)[59s:1m]), \"instance_short\", \"$1\", \"instance\", \"([\\\\w\\\\-]+).*\")\n\n",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Queue usage [% of quota]",
   "type": "graph",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "solace_queue_spool_usage_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\"} / solace_queue_spool_quota_bytes{instance=\"$instance\",vpn_name=\"$vpn_name\"} * 100",
     "legendFormat": "{{queue_name}}"
    }
   ]
  },
  {
   "title": "Spool memory usage over vpn [% of quota]",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 56 },
   "yaxes": [
    { "format": "short", "label": "%" }
   ],
   "targets": [
    {
     "expr": "100*solace_vpn_spool_usage_bytes{instance=\"$instance\", vpn_name=\"$vpn_name\"}/solace_vpn_spool_quota_bytes{instance=\"$instance\", vpn_name=\"$vpn_name\"}"
    }
   ]
  },
  {
   "title": "Spool messages over vpn",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 64 },
   "yaxes": [
    { "format": "short", "label": "number of messages" }
   ],
   "targets": [
    {
     "expr": "solace_vpn_spool_usage_msgs{instance=\"$instance\", vpn_name=\"$vpn_name\"}"
    }
   ]
  }
 ]
}